# Server settings
server:
    port: 8888
    address: 127.0.0.1

# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    mvc:
        view.prefix: /WEB-INF/jsp/
        view.suffix: .jsp

    # DATASOURCE
    datasource:
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/fcis?useUnicode=true&characterEncoding=utf-8&&useSSL=true
        username: root
        password: root
        hikari:
            maxLifetime: 30000
            maximumPoolSize: 15
mybatis:
    mapperLocations: classpath:mapper/*.xml

mypops:
    name: abc
    age: 12